name: CI

on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
  coverage:
    name: Coverage for ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/codecov')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - uses: Swatinem/rust-cache@v1
        with:
          key: coverage-cargo-${{ matrix.os }}
        continue-on-error: true
      - name: Setup virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r py-polars/requirements-dev.txt
      - name: Run coverage
        run: |
          source venv/bin/activate
          source <(cargo llvm-cov show-env --export-prefix)
          export CARGO_TARGET_DIR=$CARGO_LLVM_COV_TARGET_DIR
          export CARGO_INCREMENTAL=1
          cd py-polars
          cargo llvm-cov clean --workspace
          cargo test
          maturin develop
          pytest tests --cov=polars --cov-report xml
          cargo llvm-cov --no-run --lcov --output-path coverage.lcov
      - uses: codecov/codecov-action@v4
        with:
          files: coverage.lcov,coverage.xml
          name: ${{ matrix.os }}
          override_pr: 1